version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tasklist
    depends_on:
      - db
    image: tasklist_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8080:80'

  db:
      image: postgres:latest
      container_name: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=tasklist
      volumes:
        - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
