spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasklist?currentSchema=tasklist
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: TGFiYXNBc015bGl1SmF2YUppTWFuTGFiYWlQYXRpbmthVGFpU3VwZXI=
    access: 3600000
    refresh: 2592000000